name: Build and Release

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'   # e.g. v1.0.4

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]  # pin macOS

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install system deps (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm fakeroot dpkg rpm2cpio cpio
          # If you added AppImage maker, also:
          # sudo apt-get install -y squashfs-tools file

      # macOS installs optional deps (so it gets appdmg for DMG)
      - name: Install deps (macOS)
        if: matrix.os == 'macos-14'
        run: npm ci --no-audit --no-fund

      # Windows/Linux skip optional deps (so they don't try to install appdmg)
      - name: Install deps (Windows/Linux)
        if: matrix.os != 'macos-14'
        run: npm ci --omit=optional --no-audit --no-fund

      # Optional: only keep if you actually installed electron-rebuild in devDependencies.
      # Forge will rebuild native modules during `make` anyway.
      # - name: Rebuild native modules (sqlite3)
      #   run: npx electron-rebuild -f -w sqlite3

      - name: Build (Forge make)
        env:
          DEBUG: electron-forge:*     # verbose forge logs in CI
          npm_config_loglevel: warn
        run: npm run make

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: out/make/

      # Collect logs if something fails, to make debugging easy
      - name: Upload npm & forge logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-logs
          path: |
            ~/.npm/_logs/*
            **/forge-*.log
            **/*.log
          if-no-files-found: ignore

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-14-build
          path: dist/macos

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-latest-build
          path: dist/windows

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest-build
          path: dist/linux

      - name: Create draft release with all files
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          draft: true
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
